import type { EquipoCambioSemestral } from "./types"

export const equiposCambiosSemestralesMock: EquipoCambioSemestral[] = [
  {
    id: 12,
    nombre: "Equipo Centro",
    semestre: "1er semestre 2026",
    profesionales: [
      {
        id: 101,
        nombre: "Luciana",
        apellido: "Fernandez",
        dni: "30111222",
        correo: "luciana.fernandez@dae.test",
        estado: "pendiente",
        ultimaActualizacion: "23/04/2026 09:15",
        fechaEnvio: "22/04/2026 18:40",
        observacion: "Pendiente de revisión del equipo.",
      },
      {
        id: 102,
        nombre: "Martin",
        apellido: "Quiroga",
        dni: "28999111",
        correo: "martin.quiroga@dae.test",
        estado: "confirmado",
        ultimaActualizacion: "24/04/2026 10:02",
        fechaEnvio: "24/04/2026 08:18",
        observacion: "Confirmado por coordinación.",
      },
      {
        id: 103,
        nombre: "Carla",
        apellido: "Sosa",
        dni: "33444555",
        correo: "carla.sosa@dae.test",
        estado: "sin-enviar",
        ultimaActualizacion: "Sin actividad",
        observacion: "Aún no respondió el formulario.",
      },
      {
        id: 104,
        nombre: "Leandro",
        apellido: "Molina",
        dni: "27555333",
        correo: "leandro.molina@dae.test",
        estado: "rechazado",
        ultimaActualizacion: "25/04/2026 15:21",
        fechaEnvio: "25/04/2026 12:03",
        observacion: "Debe corregir superposición horaria.",
      },
    ],
  },
  {
    id: 27,
    nombre: "Equipo Norte",
    semestre: "1er semestre 2026",
    profesionales: [
      {
        id: 201,
        nombre: "Mariana",
        apellido: "Ruiz",
        dni: "31888777",
        correo: "mariana.ruiz@dae.test",
        estado: "enviado",
        ultimaActualizacion: "21/04/2026 11:05",
        fechaEnvio: "21/04/2026 11:05",
        observacion: "Enviado, pendiente de confirmación.",
      },
      {
        id: 202,
        nombre: "Diego",
        apellido: "Acosta",
        dni: "29999444",
        correo: "diego.acosta@dae.test",
        estado: "sin-enviar",
        ultimaActualizacion: "Sin actividad",
        observacion: "No abrió el enlace aún.",
      },
      {
        id: 203,
        nombre: "Noelia",
        apellido: "Vega",
        dni: "32111999",
        correo: "noelia.vega@dae.test",
        estado: "confirmado",
        ultimaActualizacion: "26/04/2026 13:47",
        fechaEnvio: "26/04/2026 09:10",
        observacion: "Carga aprobada para el semestre.",
      },
    ],
  },
  {
    id: 35,
    nombre: "Equipo Sur",
    semestre: "1er semestre 2026",
    profesionales: [
      {
        id: 301,
        nombre: "Sabrina",
        apellido: "Perez",
        dni: "34455666",
        correo: "sabrina.perez@dae.test",
        estado: "pendiente",
        ultimaActualizacion: "26/04/2026 08:32",
        fechaEnvio: "25/04/2026 17:55",
        observacion: "Pendiente de validar paquetes semestrales.",
      },
      {
        id: 302,
        nombre: "Gustavo",
        apellido: "Roldan",
        dni: "27777666",
        correo: "gustavo.roldan@dae.test",
        estado: "sin-enviar",
        ultimaActualizacion: "Sin actividad",
        observacion: "Recordatorio aún no enviado.",
      },
      {
        id: 303,
        nombre: "Paula",
        apellido: "Benitez",
        dni: "30888444",
        correo: "paula.benitez@dae.test",
        estado: "rechazado",
        ultimaActualizacion: "24/04/2026 16:18",
        fechaEnvio: "24/04/2026 10:24",
        observacion: "Debe corregir horas de GEI.",
      },
      {
        id: 304,
        nombre: "Federico",
        apellido: "Aguirre",
        dni: "29123123",
        correo: "federico.aguirre@dae.test",
        estado: "confirmado",
        ultimaActualizacion: "26/04/2026 14:02",
        fechaEnvio: "26/04/2026 08:44",
        observacion: "Confirmado por el equipo.",
      },
    ],
  },
]
